services:
  - type: web
    name: campusmart-all-in-one
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_SUPABASE_URL
        value: https://ilsrhtcxztpaedpfqbpv.supabase.co
      - key: APP_SUPABASE_KEY
        sync: false
